/* ACCOUNT TYPE */

export enum ACCOUNT_TYPE {
  GOD_ADMIN = 'GOD_ADMIN',
  STORE_ADMIN = 'STORE_ADMIN',
  DELIVERY = 'DELIVERY',
}
export enum ORDER_STATUS {
  PLACED_BY_CUSTOMER = 'PLACED_BY_CUSTOMER',
  RECEIVED_BY_STORE = 'RECEIVED_BY_STORE',
  PICKED_UP = 'PICKED_UP',
  DELIVERED_AND_PAID = 'DELIVERED_AND_PAID',
  CANCELLED_BY_STORE = 'CANCELLED_BY_STORE',
  CANCELLED_BY_CUSTOMER = 'CANCELLED_BY_CUSTOMER',
}
